
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import java.util.Arrays;
import javax.swing.*;
import javax.swing.border.Border;

import DTO.NhanVienDTO;
import DTO.TaiKhoanDTO;
import DAO.TaiKhoanDAO;

/**
 *
 * @author defaultuser0
 */
public class TaiKhoanView extends JPanel {
    
    TaiKhoanDAO dao = new TaiKhoanDAO();
    /**
     * Creates new form TaiKhoanView
     */
    Border panel_border = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.gray);
    Border textfield_border = BorderFactory.createMatteBorder(0, 0, 2, 0, Color.white);
    
    public TaiKhoanView() {
//        initComponents();
        setBorder(panel_border);
        txt_matKhau.setBorder(textfield_border);
        txt_taiKhoan.setBorder(textfield_border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void btn_dangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangNhapActionPerformed
        if (validateForm()) {
           String tk = txt_taiKhoan.getText().trim();
           char[] password = txt_matKhau.getPassword();
            String mk = new String(password);
            System.out.println(tk);
            System.out.println(mk);

            if (dao.checkLogin(tk, mk)==1) {
                JOptionPane.showMessageDialog(this, "Đăng nhập thành công");
//                this.dispose();
                NhanVienView x = new NhanVienView();
                x.setVisible(true);
            } else if(dao.checkLogin(tk, mk)==0){
                JOptionPane.showMessageDialog(this, "Tài khoản đã bị khóa");
            }else if(dao.checkLogin(tk, mk)==-1){
                JOptionPane.showMessageDialog(this, "Sai tên đăng nhập hoặc mật khẩu");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập đầy đù thông tin");
        }
    }//GEN-LAST:event_btn_dangNhapActionPerformed

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
//        this.dispose();
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void btn_dangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangKyActionPerformed
        DangKyView view = new DangKyView();
        view.setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_btn_dangKyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        this.dispose();
        QuenMatKhauGUI x = new QuenMatKhauGUI();
        x.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaiKhoanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaiKhoanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaiKhoanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaiKhoanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaiKhoanView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangKy;
    private javax.swing.JButton btn_dangNhap;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_main;
    private javax.swing.JPasswordField txt_matKhau;
    private javax.swing.JTextField txt_taiKhoan;
    // End of variables declaration//GEN-END:variables
public boolean validateForm() {
        if (txt_taiKhoan.getText().isEmpty() || txt_matKhau.getText().isEmpty()) {
            return false;
        }
        return true;
    }
    
}
